# Generated by Django 4.2.6 on 2023-10-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAssessmentHistory',
        ),
    ]
