# Generated by Django 4.2.6 on 2023-10-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0002_delete_studentassessmenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ef1_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ef2_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ef3_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ef4_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ef5_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ef6_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('cy1_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('cy2_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('cy3_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('cy4_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ex1_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ex2_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ex3_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ex4_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ex5_score', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('ex_mean', models.FloatField(blank=True, default=None, null=True)),
                ('cy_mean', models.FloatField(blank=True, default=None, null=True)),
                ('ef_mean', models.FloatField(blank=True, default=None, null=True)),
                ('ex_high', models.BooleanField(blank=True, default=None, null=True)),
                ('cy_high', models.BooleanField(blank=True, default=None, null=True)),
                ('ef_high', models.BooleanField(blank=True, default=None, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burnout_assessment.burnoutprofile')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='burnout_assessment.student')),
            ],
            options={
                'verbose_name_plural': 'student assessment history',
            },
        ),
    ]
