# Generated by Django 4.2.6 on 2023-10-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0003_studentassessmenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_boundary', models.FloatField(blank=True, default=None, null=True)),
                ('cy_boundary', models.FloatField(blank=True, default=None, null=True)),
                ('ef_boundary', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'critical boundaries',
            },
        ),
    ]
