# Generated by Django 4.2.6 on 2023-11-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0004_criticalboundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='code',
            field=models.CharField(blank=True, default='None', max_length=5, null=True),
        ),
    ]
