# Generated by Django 4.2.6 on 2023-11-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0005_college_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
