# Generated by Django 4.2.6 on 2023-11-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0009_counselor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsurveyquestion',
            options={'ordering': ['-id'], 'verbose_name_plural': 'student survey questions'},
        ),
    ]
