# Generated by Django 4.2.6 on 2023-12-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0011_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
