# Generated by Django 4.2.6 on 2024-01-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0012_student_email_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_verification_code',
        ),
    ]
