# Generated by Django 5.0.1 on 2024-02-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0013_remove_student_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
