# Generated by Django 5.0.1 on 2024-02-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0015_alter_student_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
