# Generated by Django 5.0.1 on 2024-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0019_assessment_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assessment_exists',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
