# Generated by Django 5.0.1 on 2024-03-21 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0020_student_assessment_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
