# Generated by Django 5.0.1 on 2024-03-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0021_alter_assessment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
