# Generated by Django 5.0.1 on 2024-04-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0022_assessment_is_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_profile_updated',
            new_name='is_password_updated',
        ),
    ]
