# Generated by Django 5.0.1 on 2024-04-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0023_rename_is_profile_updated_student_is_password_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='is_assessment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
