# Generated by Django 5.0.1 on 2024-04-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0025_student_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
    ]
