# Generated by Django 5.0.1 on 2024-04-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout_assessment', '0026_remove_student_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
